name: 02 - Workflow Events

on: 
  push:
  pull_request:
  schedule: 
    - cron: '0 21 * * 3'
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: echo event
        run: echo "Event name is ${{ github.event_name }}"
       
