name: 04 Using Actions

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        uses: actions/setup-node@4
        with:
          node-version: '20.x'

      - name: Setup Node
        working-directory: 04-using-actions/react-app
        run: npm run test
