name: 04 Using Actions

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        run: uses/checkout@v4

      - name: Printing Folders
        run: |
          cd 04-using-actions
          ls -ltra
